# - С душой, с любовью, с бессонной ночи от EatherBone - #

# - Анти Флуд - #
timeout:
  softness: 2000 # Задержка между сообщениями в мс (1000 = 1 секунда)"

# - Фильтр Чата - #
filter:
  attempts_limit: 4 # Количество сообщений с банвордами подряд до авто-мута

# - Анти Капс - #
anticaps:
  min_length: 10 # Мин. длина
  threshold: 0.3 # порог капса в % (По умолчанию 0.3 = 30%)

# --- Конструктор авто-мута --- #
auto-mute-settings:
  # Команда, которая будет выполняться от имени консоли.
  # Доступные плейсхолдеры: {player}, {time}, {reason}
  # ПРИМЕР для Essentials: "/mute {player} {time} {reason}"
  # ПРИМЕР для другого плагина: "/tempban {player} {time} -s {reason}"
  command: "/mute {player} {time} {reason}"

  # Время наказания, которое подставится в плейсхолдер {time}
  time: "15m"

  # Причина, которая подставится в плейсхолдер {reason}
  reason: "Авто-мут за нарушение правил чата"